# Generated by Django 2.2.7 on 2019-11-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_newsletter_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name="Nom d'affichage"),
        ),
    ]
