# Generated by Django 2.2.7 on 2019-11-25 14:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20191125_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('urgent_level', models.PositiveSmallIntegerField(default=3, help_text="Entre 0 (bas niveau d'urgence) et 10 (urgence critique)", validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name="Niveau d'urgence")),
            ],
            options={
                'verbose_name': "Catégorie d'appel",
                'verbose_name_plural': "Catégories d'appels",
            },
        ),
        migrations.CreateModel(
            name='CallTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Tag d'appel",
                'verbose_name_plural': "Tags d'appels",
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name="Contenu de l'appel")),
                ('solved', models.BooleanField(db_index=True, default=False, verbose_name='Résolu')),
                ('customer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Customer', verbose_name='Client')),
                ('tags', models.ManyToManyField(to='calls.CallTag', verbose_name='Tags')),
                ('teammember', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.TeamMember', verbose_name="Membre d'équipe")),
            ],
            options={
                'verbose_name': 'Appel',
                'verbose_name_plural': 'Appels',
            },
        ),
    ]
