# Generated by Django 2.2.7 on 2019-11-26 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calls.CallCategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='callcategory',
            name='urgent_level',
            field=models.PositiveSmallIntegerField(default=3, help_text="Entre 1 (bas niveau d'urgence) et 10 (urgence critique)", validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name="Niveau d'urgence"),
        ),
    ]
